services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-multi-db
    platform: linux/amd64
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
      - MSSQL_PID=Express
      - MSSQL_TCP_PORT=1433
    ports:
      - "1433:1433"
    volumes:
      - ./scripts:/scripts:ro
      - ./entrypoint.sh:/entrypoint.sh:ro
      - mssql_data:/var/opt/mssql
    entrypoint: ["/bin/bash", "/entrypoint.sh"]
    healthcheck:
      test: [
        "CMD-SHELL", 
        "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P YourStrong!Passw0rd -C -Q 'SELECT 1' -N -l 1 || exit 1"
      ]
      interval: 15s
      retries: 10
      start_period: 90s
      timeout: 5s
    restart: unless-stopped

volumes:
  mssql_data: