services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-CU10-ubuntu-22.04
    container_name: sqlserver-multi-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - ./scripts:/scripts:ro
      - ./entrypoint.sh:/entrypoint.sh:ro
      - mssql_data:/var/opt/mssql
    entrypoint: ["/bin/bash", "/entrypoint.sh"]
    healthcheck:
      test: [
        "CMD-SHELL", 
        "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P YourStrong!Passw0rd -C -Q 'SELECT 1' || exit 1"
      ]
      interval: 30s
      retries: 5
      start_period: 60s
      timeout: 10s
    restart: unless-stopped

volumes:
  mssql_data: