org: devploy

service: neo-auth
frameworkVersion: '4.14.3'

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-2
  stage: dev
  environment:
    STAGE: ${sls:stage}
    DB_NEO_HOST: ${ssm:/neo-auth/db-neo/host}
    DB_NEO_PORT: ${ssm:/neo-auth/db-neo/port}
    DB_NEO_USER: ${ssm:/neo-auth/db-neo/user}
    DB_NEO_PASS: ${ssm:/neo-auth/db-neo/pass}
    DB_NEO_NAME: ${ssm:/neo-auth/db-neo/name}
    #DB_BILL_HOST: ${ssm:/neo-auth/db-bill/host}
    #DB_BILL_PORT: ${ssm:/neo-auth/db-bill/port}
    #DB_BILL_USER: ${ssm:/neo-auth/db-bill/user}
    #DB_BILL_PASS: ${ssm:/neo-auth/db-bill/pass}
    #DB_BILL_NAME: ${ssm:/neo-auth/db-bill/name}
    #DB_TANTRA_HOST: ${ssm:/neo-auth/db-tantra/host}
    #DB_TANTRA_PORT: ${ssm:/neo-auth/db-tantra/port}
    #DB_TANTRA_USER: ${ssm:/neo-auth/db-tantra/user}
    #DB_TANTRA_PASS: ${ssm:/neo-auth/db-tantra/pass}
    #DB_TANTRA_NAME: ${ssm:/neo-auth/db-tantra/name}
    SUBNET_ID: ${ssm:/neo-auth/vpc/sn-id}
    SECURITY_GROUP_ID: ${ssm:/neo-auth/vpc/sg-id}
  
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - ec2:CreateNetworkInterface
            - ec2:DescribeNetworkInterfaces
            - ec2:DeleteNetworkInterface
          Resource: "*"

plugins:
  - serverless-offline

functions:
  main:
    handler: dist/handler.handler
    timeout: 20
    memorySize: 128
    vpc:
      securityGroupIds:
        - ${self:provider.environment.SECURITY_GROUP_ID}
      subnetIds:
        - ${self:provider.environment.SUBNET_ID}
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'

custom:
  serverless-offline:
    useChildProcesses: true
    httpPort: 3000
  esbuild:
    tsconfig: './tsconfig.json'
    bundle: true
    minify: false
    sourcemap: true
    exclude: ['aws-sdk']
    target: node20
    platform: node
    concurrency: 10

package:
  patterns:
    - '!node_modules/.cache/**'
    - '!node_modules/**/test/**'
    - '!node_modules/**/tests/**'
    - '!node_modules/**/*.md'
    - '!node_modules/**/*.ts'
    - '!node_modules/**/*.map'
    - '!node_modules/**/LICENSE*'
    - '!node_modules/**/CHANGELOG*'
    - '!node_modules/**/README*'
    - '!node_modules/**/docs/**'
    - '!node_modules/**/examples/**'
    - '!node_modules/**/.github/**'
    - '!src/**'
    - '!test/**'
    - '!*.md'
    - '!.git/**'
    - '!.vscode/**'
    - '!.serverless/**'
    - '!docker-compose.yml'
    - '!Dockerfile'
    - '!entrypoint.sh'
    - 'dist/**'